module.exports = {
  main: '/',
  dashboard: '/dashboard/',
  forgotPassword: '/auth/forgorPassword',
  login: '/auth/login',
  register: '/auth/register',
  profile: '/dashboard/user/profile',
  requests: '/dashboard/requests',
  inquiries: '/dashboard/inquiries',
  wallet: '/dashboard/wallet',
  management: '/dashboard/management',
  myAccount: '/dashboard/myAccount',
  messages: '/dashboard/messages',
  offers: '/dashboard/offers',
}
