module.exports = {
  main: '/',
  dashboard: '/dashboard',
  forgotPassword: '/auth/forgorPassword',
  login: '/auth/login',
  register: '/auth/register',
  profile: '/user/profile',
  requests: '/requests',
  inquiries: '/inquiries',
  wallet: '/wallet',
  management: '/management',
  myAccount: '/myAccount',
  messages: '/messages',
  offers: '/offers',
}
